ai_goals:
- Use the write_file command to write 'Hello World' into a file
- Use the task_complete command to complete the task
- Do not use any other commands
ai_name: task_complete-GPT
ai_role: an AI designed to use the write_file command to write 'Hello World' into
  a file and then use the task_complete command to complete the task
interactive_input: false
