name: Python CI

on:
  push:
    branches: [ master, ci-test* ]
  pull_request_target:
    branches: [ master, stable, ci-test* ]

concurrency:
  group: ${{ format('ci-{0}', github.head_ref && format('pr-{0}', github.event.pull_request.number) || github.sha) }}
  cancel-in-progress: ${{ github.event_name == 'pull_request_target' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      min-python-version: "3.10"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Python ${{ env.min-python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.min-python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8

      - name: Check black formatting
        run: black . --check
        if: success() || failure()

      - name: Check isort formatting
        run: isort . --check
        if: success() || failure()

      - name: Check mypy formatting
        run: mypy
        if: success() || failure()

  test:
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittest tests with coverage
        run: |
          pytest -s tests/integration/challenges/basic_abilities/test_write_file.py
        env:
          CI: true
          PROXY: ${{ secrets.PROXY }}
          AGENT_MODE: ${{ vars.AGENT_MODE }}
          AGENT_TYPE: ${{ vars.AGENT_TYPE }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Stage new files, commit, and check for new cassettes
        id: stage_files
        run: |
          git fetch origin ${{ github.base_ref }}

          git add tests
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git commit -m "Add new cassettes"
          TIMESTAMP_COMMIT=$(date +%Y%m%d%H%M%S) # generate a timestamp
          echo "TIMESTAMP_COMMIT=TIMESTAMP_COMMIT" >> $GITHUB_ENV

          # Check for new cassettes added in PR after the commit
          NEW_CASSETTES_ADDED_IN_PR=$(git diff --name-only $(git merge-base ${{ github.event.pull_request.base.sha }} HEAD)..HEAD -- 'tests/**/cassettes/**/*.yaml' | wc -l)
          if [[ "$NEW_CASSETTES_ADDED_IN_PR" -gt 0 ]]
          then 
            echo "NEW_CASSETTES_ADDED_IN_PR=true" >> $GITHUB_ENV
          else 
            echo "NEW_CASSETTES_ADDED_IN_PR=false" >> $GITHUB_ENV
          fi
      

      - name: Beat new challenges
        if: ${{ env.NEW_CASSETTES_ADDED_IN_PR}}
        run: |
          echo "This step will run the challenges soon."

      - name: Create PR
        id: create_pr
        if:  ${{ env.TIMESTAMP_COMMIT != null }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update cassettes and challenges score
          branch: cassette-diff-PR-${{ github.event.pull_request.number }}-${{ env.TIMESTAMP_COMMIT }}
          title: "Update cassette-diff-PR${{ github.event.pull_request.number }}-${{ env.TIMESTAMP_COMMIT }}"
          body: "This PR updates the cassettes and the challenges score if it changed. Please merge it."

      - name: Comment PR URL in the current PR
        if:  ${{ env.TIMESTAMP_COMMIT != null }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Please click [HERE](${{ steps.create_pr.outputs.pull-request-url }}) and merge this PR to update the cassettes.

      - name: Fail if new PR created
        if:  ${{ env.TIMESTAMP_COMMIT != null }}
        run: exit 1
